import { createContext, useContext, useState, ReactNode } from "react";

type Language = "az" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  az: {
    // Navbar
    "nav.services": "Xidmətlər",
    "nav.about": "Haqqımızda",
    "nav.contact": "Əlaqə",
    "nav.download": "Yüklə",

    // Hero
    "hero.title": "Çamaşırxana ehtiyaclarınızı həll etməyin ən asan yolu.",
    "hero.description": "Paltarlarınızı sizdən götürür, təmizləyib və çatdırırıq. Rahatınızda qalın və ürəyiniz istədiyiniz zaman mobil tətbiq üzərindən sifariş edin.",
    "hero.pickup": "Ünvandan götürülmə və çatdırılma",
    "hero.support": "24/7 müştəri xidməti",
    "hero.status": "Canlı statuslar",
    "hero.downloadApp": "Tətbiqi Yüklə",
    "hero.moreInfo": "Ətraflı Məlumat",

    // Feature Block
    "features.title": "Vaxtınız özünüzə qalsın. Camaşırxana işlərinizi isə bizə həvalə edin.",
    "features.online.title": "Tam online sifariş",
    "features.online.description": "Sizə uyğun vaxtda paltarlarınızı hazırlayın və mobil tətbiq üzərindən bizi çağırın.",
    "features.professional.title": "Professional təmizləmə, qayğı ilə",
    "features.professional.description": "Təmizlənmə nəticələrinə şəxsən nəzarət edirik, özü də sizə ən yaxın məntəqədə.",
    "features.delivery.title": "Qapıya çatdırılma",
    "features.delivery.description": "Dəyərli vaxtınıza qənaət edin. Biz isə təmiz paltarlarınızı birbaşa qapınıza çatdırarıq.",

    // Three Steps
    "steps.title": "Bu qədər rahatlıq cəmi 3 addımda",
    "steps.subtitle": "Sifariş vermək heç vaxt bu qədər asan olmamışdı",
    "steps.step1.title": "Tətbiqdən şifarişinizi edin",
    "steps.step1.description": "Gününüzü rahat planlayın, götürülmə və çatdırılma tarixini özünüz seçin.",
    "steps.step2.title": "Kuryeri gözləyin",
    "steps.step2.description": "Siz qeyd etdiyiniz vaxtda kuryer qapınızda olacaqdır. Paltarlarınızı paketləyib sizdən təhvil alacağıq.",
    "steps.step3.title": "Rahatınızda qalın və çatdırılmanı gözləyin",
    "steps.step3.description": "Paltarlarınızı təmizlədikdən sonra sifariş etdiyiniz qaydada, göstərdiyiniz tarixdə geri gətirəcəyik.",

    // Services
    "services.title": "Xidmətlərimiz",
    "services.dryCleaning.title": "Quru təmizləmə",
    "services.dryCleaning.slogan": "Etibarlı şəkildə, ilk günkü kimi.",
    "services.washing.title": "Yuma",
    "services.washing.slogan": "Kiloqram ilə, xüsusi qayğı ilə.",
    "services.ironing.title": "Ütüləmə",
    "services.ironing.slogan": "Ən şık görünəcək vəziyyətdə.",

    // About
    "about.title": "Yom Haqqında",
    "about.description": "Yom ölkəmizdə mobil tətbiqi vasitəsilə istifadəçilərə camaşırxana xidmətlərini təklif ilk platformadır. Məqsədimiz, camaşırxana işlərini asanlaşdırmaqla insanlara vaxtlarını daha səmərəli istifadə etmək imkanı yaratmaqdır. Çünki camaşır işləri bir həftədə 3 saatdan çox vaxtımızı alır və bir çox hallarda sıxıcı bir proses ola bilir. İnanırıq ki bu yolda ən keyfiyyətli çatdırılma və təmizləmə xidmətləri təklif etmək və insanlara bunu ən rahat şəkildə əlçatan etmək bu hədəfimizə gedən əsas yoldur.",

    // FAQ
    "faq.title": "Sualınız var? Biz buradayıq",
    "faq.button": "Sualınızı bizdən soruşun",
    "faq.q1": "Hansı bölgələrdə xidmət göstərirsiniz?",
    "faq.a1": "Hazırda sadəcə Bakı şəhərinin mərkəz ərazilərində xidmət göstəririk. Yaxın gələcəkdə isə durmadan böyüyərək Azərbaycanın bütün bölgələrinə xidmət göstərməyi hədəfləyirik.",
    "faq.q2": "Kuryerlər hansı aralıqda işləyirlər?",
    "faq.a2": "Əlbəttə ki sizə ən uyğun vaxtda. Bu seçimi tam siz edirsiniz. Mobil tətbiqdə təhvil alma və təslim vaxtlarını seçin, gerisini isə bizə buraxın.",
    "faq.q3": "Ödənişləri necə edə bilərəm?",
    "faq.a3": "Ödənişinizi tam onlayn ödəyə bilərsiniz. Hazırda, nəğd ödənişləri təəssüf ki qəbul etmirik.",
    "faq.q4": "Sifarişimi dəyişdirə və ya ləğv edə bilərəm?",
    "faq.a4": "Əlbəttə. Bunu bizim müştəri xidmətlərinə bildirməyiniz yetərli olacaqdır.",

    // Download
    "download.title": "Təmiz paltarlarınız bir toxunuş qədər uzaqda",
    "download.description": "Mobil tətbiqimizi elə indi yükləyin və xidmətimizin rahatlığından dəqiqələr içində istifadə edin.",
    "download.scanToDownload": "Yükləmək üçün skan edin",

    // Footer
    "footer.description": "Peşəkar camaşırxana və quru təmizləmə xidmətləri qapınıza çatdırılır.",
    "footer.services": "Xidmətlər",
    "footer.laundry": "Camaşırxana",
    "footer.dryCleaning": "Quru Təmizləmə",
    "footer.express": "Ekspress Xidmət",
    "footer.scheduled": "Planlaşdırılmış Götürmə",
    "footer.company": "Şirkət",
    "footer.about": "Haqqımızda",
    "footer.contact": "Əlaqə",
    "footer.legal": "Hüquqi",
    "footer.privacy": "Məxfilik Siyasəti",
    "footer.terms": "Xidmət Şərtləri",
    "footer.rights": "Bütün hüquqlar qorunur.",

    // Contact Page
    "contact.title": "Əlaqə",
    "contact.description": "Bizimlə əlaqə saxlayın. Suallarınız, təklifləriniz və ya şikayətləriniz üçün bizə yazın.",
    "contact.info": "Əlaqə Məlumatları",
    "contact.address": "Ünvan",
    "contact.phone": "Telefon",
    "contact.email": "E-poçt",
    "contact.social": "Sosial Mediada YOM",
    "contact.followLinkedIn": "LinkedIn-də bizi izləyin",
    "contact.followInstagram": "Instagram-da bizi izləyin",

    // Terms Page
    "terms.title": "İstifadəçi Şərtləri",
    "terms.lastUpdated": "Son yenilənmə tarixi: 19.11.2025",
    "terms.section1.title": "1. Haqqımızda",
    "terms.section1.p1": "\"Yom\" mobil tətbiqi vasitəsilə istifadəçilərə (\"siz\", \"sizin\") camaşırxana xidmətlərini sifariş etmək imkanı verən platformadır. Bu xidmətlərə paltar yuma, quru təmizləmə, xalça yuma və ya digər oxşar təmizləmə xidmətləri aiddir. Platforma (\"Yom\", \"biz\", \"bizim\") tərəfindən UÇOT nömrəsi (VÖEN) 2005163372 ilə tənzimlənilir.",
    "terms.section1.p2": "Məqsədimiz, camaşırxana işlərini asanlaşdırmaqla insanlara vaxtlarını daha səmərəli istifadə etmək imkanı yaratmaqdır. Çünki ilkin araşdırmalarımız onu göstərir ki, camaşır işləri bir həftədə 3 saatdan çox vaxtımızı alır və sıxıcı bir prosesdir.",
    "terms.section1.p3": "Hədəfimiz isə istifadəçilərimizin bütün camaşır ehtiyaclarını ən asan yolla həll etmək imkanı yaratmaqdır. İnanırıq ki bu yolda ən keyfiyyətli çatdırılma və təmizləmə xidmətləri təklif etmək və insanlara bunu ən rahat şəkildə əlçatan etmək bu hədəfimizə gedən əsas yoldur.",
    "terms.section1.p4": "Onu da qeyd edək ki, \"Yom\" agent kimi fəaliyyət göstərir – yəni \"Yom\" çamaşırxana və ya təmizləmə mərkəzlərinə malik deyil, yalnız:",
    "terms.section1.li1": "müştəriləri müstəqil xidmət təminatçıları ilə əlaqələndirir;",
    "terms.section1.li2": "geyimlərin və əşyaların götürülməsi və çatdırılmasını təşkil edir.",
    "terms.section1.p5": "\"Yom\"-dan istifadə etməklə siz bu İstifadə Şərtləri (\"Şərtlər\") ilə razı olduğunuzu təsdiqləyirsiniz.",
    "terms.section2.title": "2. Yom-un rolu",
    "terms.section2.p1": "Yom heç bir təmizləmə müəssisəsinə sahib deyil və onların fəaliyyətinə nəzarət etmir.",
    "terms.section2.p2": "Yom-un rolu aşağıdakılardan ibarətdir:",
    "terms.section2.li1": "müştəriləri müstəqil təmizləmə xidmətləri göstərən tərəfdaşlarla əlaqələndirmək;",
    "terms.section2.li2": "əşyaların götürülməsi və çatdırılmasını təşkil etmək;",
    "terms.section2.li3": "ödənişlərin və əlaqələrin idarə olunmasını təmin etmək.",
    "terms.section2.p3": "Təmizləmə işlərinin icrası yalnız müstəqil xidmət təminatçıları tərəfindən həyata keçirilir. Onlar öz biznes fəaliyyətlərinə və nəticələrinə görə məsuliyyət daşıyırlar.",
    "terms.section3.title": "3. Şərtlərin qəbul edilməsi",
    "terms.section3.p1": "Yom tətbiqində qeydiyyatdan keçməklə, sifariş yerləşdirməklə və ya tətbiqdən istifadə etməklə siz:",
    "terms.section3.li1": "18 yaşınızın tamam olduğunu;",
    "terms.section3.li2": "bu Şərtləri oxuyub başa düşdüyünüzü; və",
    "terms.section3.li3": "onlara əməl etməyə razı olduğunuzu təsdiqləyirsiniz.",
    "terms.section3.p2": "Əgər bu şərtlərlə razı deyilsinizsə, tətbiqdən istifadə etməyin.",
    "terms.section4.title": "4. Sifarişlərin yerləşdirilməsi",
    "terms.section4.p1": "Sifariş verdikdə:",
    "terms.section4.li1": "Siz Yom vasitəsilə götürülmə və çatdırılma xidməti sifariş edirsiniz;",
    "terms.section4.li2": "Yom sizin əşyalarınızı təmizlənməsi üçün tərəfdaş çamaşırxanalardan birinə yönləndirir;",
    "terms.section4.li3": "Hansı xidmət təminatçısının seçildiyi sizə göstərilmir, bu proses Yom tərəfindən daxili qaydada idarə olunur.",
    "terms.section4.p2": "Sifariş təsdiqlənməklə siz Yom-a:",
    "terms.section4.li4": "sizin adınızdan xidmət sifariş etmək,",
    "terms.section4.li5": "ödənişləri və əlaqəni təmin etmək səlahiyyəti verirsiniz.",
    "terms.section5.title": "5. Götürülmə və çatdırılma",
    "terms.section5.p1": "Yom əşyalarınızı təyin etdiyiniz ünvandan götürəcək və təmizlənmədən sonra geri gətirəcəkdir.",
    "terms.section5.p2": "Əşyaların götürülməsi və çatdırılması üçün təxmini vaxt tətbiqdə göstərilir, lakin bu, hava, nəqliyyat və digər səbəblərdən dəyişə bilər.",
    "terms.section5.p3": "Siz aşağıdakılara məsuliyyət daşıyırsınız:",
    "terms.section5.li1": "əşyalar barədə düzgün məlumat vermək (material, xüsusi təlimatlar və s.);",
    "terms.section5.li2": "mövcud zədələnmələr barədə əvvəlcədən məlumat vermək.",
    "terms.section6.title": "6. Ödəniş və qiymətlər",
    "terms.section6.p1": "Tətbiqdə göstərilən qiymətlər həm Yom-un agent xidməti, həm də xidmət təminatçısının təmizləmə haqqını əhatə edir.",
    "terms.section6.p2": "Ödəniş sifariş zamanı tətbiq vasitəsilə həyata keçirilir.",
    "terms.section6.p3": "Yom qiymətləri və ya xidmət haqlarını istənilən vaxt dəyişmək hüququna malikdir. Bu dəyişikliklər yalnız yeni sifarişlərə tətbiq olunur.",
    "terms.section7.title": "7. Əşyaların itməsi və ya zədələnməsi",
    "terms.section7.p1": "Yom və tərəfdaşlarımız bütün əşyalarınıza diqqətlə yanaşır, lakin:",
    "terms.section7.li1": "Təmizləmə prosesində yaranan itki, ləkə, rəng dəyişikliyi, büzülmə və ya zədələnməyə görə Yom məsuliyyət daşımır.",
    "terms.section7.li2": "Yom-un məsuliyyəti yalnız götürülmə və çatdırılma xidmətləri ilə məhdudlaşır.",
    "terms.section7.li3": "Əgər problem yaranarsa, Yom müştəriyə xidmət təminatçısı ilə əlaqə saxlayaraq məsələnin həllinə yardım göstərəcəkdir, lakin birbaşa zərərin əvəzini ödəmək öhdəliyinə malik deyil.",
    "terms.section7.p2": "Zədələnmə və ya itki barədə iddialar çatdırılmadan sonra 24 saat ərzində Yom-a bildirilməlidir.",
    "terms.section8.title": "8. Məsuliyyətin məhdudlaşdırılması",
    "terms.section8.p1": "Qanunla icazə verilən maksimum həddə qədər:",
    "terms.section8.p2": "Yom aşağıdakı hallarda yaranan hər hansı birbaşa və ya dolayı zərərlərə görə məsuliyyət daşımır:",
    "terms.section8.li1": "Xidmət təminatçılarının hərəkət və ya hərəkətsizliyi;",
    "terms.section8.li2": "Çatdırılma və ya götürülmədə gecikmələr;",
    "terms.section8.li3": "İstifadəçi tərəfindən verilmiş yanlış və ya natamam məlumatlar.",
    "terms.section8.p3": "Yom-un ümumi məsuliyyəti, hər bir hadisə üçün, yalnız həmin sifarişə görə ödənilmiş ümumi məbləğlə məhdudlaşır.",
    "terms.section9.title": "9. İstifadəçi öhdəlikləri",
    "terms.section9.p1": "İstifadəçi razılaşır ki:",
    "terms.section9.li1": "düzgün ünvan və əlaqə məlumatı təqdim edəcək;",
    "terms.section9.li2": "təyin edilmiş vaxtda əşyaların götürülməsini təmin edəcək;",
    "terms.section9.li3": "qadağan olunmuş əşyaları (pul, zinət əşyası, təhlükəli maddələr və s.) daxil etməyəcək;",
    "terms.section9.li4": "Yom əməkdaşlarına və xidmət təminatçılarına qarşı etik davranacaq.",
    "terms.section9.p2": "Əgər götürülmə və ya çatdırılma uğursuz olarsa (məsələn, səhv ünvan, müştərinin olmaması və s.), Yom əlavə çatdırılma haqqı tələb edə bilər.",
    "terms.section10.title": "10. Ləğv və geri ödənişlər",
    "terms.section10.p1": "Sifariş əşyalar götürülməzdən əvvəl ləğv edilə bilər.",
    "terms.section10.p2": "Əşyalar götürüldükdən sonra sifarişin ləğvi mümkün deyil.",
    "terms.section10.p3": "Geri ödəniş yalnız Yom-un qərarı və ya qanunla tələb olunduğu hallarda həyata keçirilir.",
    "terms.section11.title": "11. Xidmət dəyişiklikləri",
    "terms.section11.p1": "Yom istənilən vaxt tətbiqin bəzi funksiyalarını dəyişdirmək, dayandırmaq və ya yeniləmək hüququna malikdir.",
    "terms.section11.p2": "Həmçinin, bu Şərtlər vaxtaşırı yenilənə bilər. Tətbiqdən istifadənin davam etdirilməsi, yenilənmiş şərtlərin qəbul edilməsi deməkdir.",
    "terms.section12.title": "12. Məxfilik",
    "terms.section12.p1": "Yom tətbiqindən istifadə etməklə siz Məxfilik Siyasətimizdə göstərilən məlumat toplama və işlənməsi qaydaları ilə razı olduğunuzu təsdiqləyirsiniz.",
    "terms.section12.p2": "Bu sənədlə tətbiqdə və vebsaytımızda tanış ola bilərsiniz.",
    "terms.section13.title": "13. Tətbiq olunan qanun və mübahisələrin həlli",
    "terms.section13.p1": "Bu Şərtlər Azərbaycan Respublikasının qanunvericiliyinə əsaslanır.",
    "terms.section13.p2": "Yaranan mübahisələr əvvəlcə qarşılıqlı razılaşma yolu ilə həll edilməlidir.",
    "terms.section13.p3": "Əgər razılıq əldə olunmazsa, mübahisələr Bakı şəhərinin səlahiyyətli məhkəmələrində baxılacaq.",
    "terms.section14.title": "14. Əlaqə",
    "terms.section14.p1": "Suallarınız və ya şikayətləriniz üçün bizimlə əlaqə saxlayın:",

    // Privacy Page
    "privacy.title": "Məxfilik Siyasəti",
    "privacy.lastUpdated": "Son yenilənmə tarixi: 19.11.2025",
    "privacy.section1.title": "1. Giriş",
    "privacy.section1.p1": "Yom-a xoş gəlmisiniz.",
    "privacy.section1.p2": "Bu Məxfilik Siyasəti Yom (\"Yom\", \"biz\", \"bizim\") tərəfindən idarə olunan mobil tətbiq, vebsayt və əlaqəli xidmətlərdən (\"Platforma\") istifadə zamanı şəxsi məlumatlarınızın necə toplanması, istifadəsi və qorunmasını izah edir.",
    "privacy.section1.p3": "Platformadan istifadə etməklə bu Məxfilik Siyasətinə razı olduğunuzu təsdiqləyirsiniz.",
    "privacy.section2.title": "2. Topladığımız məlumatlar",
    "privacy.section2.p1": "Yom aşağıdakı məlumatları toplaya bilər:",
    "privacy.section2.subtitle1": "a. Şəxsi məlumatlar",
    "privacy.section2.li1": "Ad və soyad",
    "privacy.section2.li2": "Telefon nömrəsi",
    "privacy.section2.li3": "E-poçt ünvanı",
    "privacy.section2.li4": "Götürülmə və çatdırılma ünvanları",
    "privacy.section2.li5": "Ödəniş məlumatları (kart məlumatlarınız Yom tərəfindən saxlanılmır, onlar etibarlı ödəniş tərəfdaşları vasitəsilə emal olunur)",
    "privacy.section2.subtitle2": "b. İstifadə məlumatları",
    "privacy.section2.li6": "Tətbiqdən istifadə tarixi və funksiyalar",
    "privacy.section2.li7": "Cihaz məlumatları (model, əməliyyat sistemi, IP ünvanı)",
    "privacy.section2.li8": "Yer məlumatı (yalnız icazə verdiyiniz halda – götürülmə və çatdırılma üçün)",
    "privacy.section3.title": "3. Məlumatların istifadə məqsədi",
    "privacy.section3.p1": "Toplanmış məlumatlar aşağıdakı məqsədlərlə istifadə olunur:",
    "privacy.section3.li1": "Hesabınızın yaradılması və idarə olunması",
    "privacy.section3.li2": "Sifarişlərin emalı və çatdırılması",
    "privacy.section3.li3": "Sizinlə sifarişlər və ödənişlər barədə əlaqə",
    "privacy.section3.li4": "Xidmət keyfiyyətinin və istifadəçi təcrübəsinin yaxşılaşdırılması",
    "privacy.section3.li5": "Qanuni öhdəliklərin yerinə yetirilməsi",
    "privacy.section4.title": "4. Məlumatların paylaşılması",
    "privacy.section4.p1": "Şəxsi məlumatlar aşağıdakı tərəflərlə paylaşılır:",
    "privacy.section4.li1": "Təmizləmə xidmət təminatçıları – sifariş etdiyiniz xidmətin icrası üçün",
    "privacy.section4.li2": "Çatdırılma tərəfdaşları və sürücülər – əşyaların götürülməsi və qaytarılması üçün",
    "privacy.section4.li3": "Ödəniş sistemləri – ödənişlərin təhlükəsiz həyata keçirilməsi üçün",
    "privacy.section4.li4": "Dövlət orqanları – qanunla tələb olunduğu hallarda",
    "privacy.section4.p2": "Yom şəxsi məlumatlarınızı heç bir halda satmır və ya icarəyə vermir.",
    "privacy.section5.title": "5. Məlumatların saxlanması",
    "privacy.section5.p1": "Məlumatlar yalnız:",
    "privacy.section5.li1": "xidmətin göstərilməsi; və",
    "privacy.section5.li2": "hüquqi və vergi öhdəliklərinin yerinə yetirilməsi müddətində saxlanılır.",
    "privacy.section5.p2": "Bu müddət bitdikdən sonra məlumatlar təhlükəsiz şəkildə silinir və ya anonimləşdirilir.",
    "privacy.section6.title": "6. Məlumatların təhlükəsizliyi",
    "privacy.section6.p1": "Yom şəxsi məlumatların qorunması üçün müvafiq texniki və inzibati tədbirlər görür.",
    "privacy.section6.p2": "Lakin internet üzərindən məlumat ötürülməsi tam təhlükəsiz olmadığından, Yom tam zəmanət verə bilmir.",
    "privacy.section7.title": "7. Sizin hüquqlarınız",
    "privacy.section7.p1": "Mövcud qanunvericiliyə əsasən siz aşağıdakı hüquqlara maliksiniz:",
    "privacy.section7.li1": "şəxsi məlumatlarınıza çıxış;",
    "privacy.section7.li2": "düzəliş və ya silinmə tələbi;",
    "privacy.section7.li3": "məlumatların işlənməsinə razılığın geri götürülməsi;",
    "privacy.section7.li4": "məlumatlarınızın surətinin tələb edilməsi.",
    "privacy.section7.p2": "Bu hüquqları həyata keçirmək üçün bizimlə əlaqə saxlayın: hello@yom.az",
    "privacy.section8.title": "8. Kukilər və izləmə texnologiyaları",
    "privacy.section8.p1": "Platforma kukilərdən (cookies) istifadə edə bilər:",
    "privacy.section8.li1": "tətbiqin funksionallığını artırmaq;",
    "privacy.section8.li2": "istifadə təcrübəsini yaxşılaşdırmaq;",
    "privacy.section8.li3": "trafiki analiz etmək üçün.",
    "privacy.section8.p2": "İstəsəniz, cihaz və ya brauzer parametrlərindən kukiləri deaktiv edə bilərsiniz.",
    "privacy.section9.title": "9. Üçüncü tərəf keçidləri",
    "privacy.section9.p1": "Platformada üçüncü tərəflərə məxsus keçidlər ola bilər.",
    "privacy.section9.p2": "Yom bu saytların məxfilik siyasətinə və fəaliyyətinə görə məsuliyyət daşımır.",
    "privacy.section10.title": "10. Siyasətə dəyişikliklər",
    "privacy.section10.p1": "Yom bu Məxfilik Siyasətini vaxtaşırı yeniləyə bilər.",
    "privacy.section10.p2": "Yenilənmiş versiya Platformada yerləşdiriləcək və tarix yenilənəcəkdir.",
    "privacy.section10.p3": "Platformadan istifadənin davam etdirilməsi yenilənmiş siyasətin qəbul edilməsi deməkdir.",
    "privacy.section11.title": "11. Əlaqə",
    "privacy.section11.p1": "Məxfilik Siyasəti ilə bağlı suallar üçün bizimlə əlaqə saxlayın:",
  },
  en: {
    // Navbar
    "nav.services": "Services",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.download": "Download",

    // Hero
    "hero.title": "The easiest way to solve your laundry needs.",
    "hero.description": "We pick up your clothes, clean them, and deliver them back. Stay comfortable and order anytime through our mobile app.",
    "hero.pickup": "Door-to-door pickup & delivery",
    "hero.support": "24/7 customer support",
    "hero.status": "Live tracking",
    "hero.downloadApp": "Download App",
    "hero.moreInfo": "Learn More",

    // Feature Block
    "features.title": "Save your time for yourself. Leave the laundry work to us.",
    "features.online.title": "Fully online ordering",
    "features.online.description": "Prepare your clothes at your convenience and call us through the mobile app.",
    "features.professional.title": "Professional cleaning with care",
    "features.professional.description": "We personally supervise the cleaning results at the nearest facility.",
    "features.delivery.title": "Door-to-door delivery",
    "features.delivery.description": "Save your valuable time. We deliver your clean clothes directly to your door.",

    // Three Steps
    "steps.title": "This much convenience in just 3 steps",
    "steps.subtitle": "Ordering has never been this easy",
    "steps.step1.title": "Place your order from the app",
    "steps.step1.description": "Plan your day easily, choose the pickup and delivery dates yourself.",
    "steps.step2.title": "Wait for the courier",
    "steps.step2.description": "The courier will be at your door at the time you specified. We'll pack and collect your clothes.",
    "steps.step3.title": "Relax and wait for delivery",
    "steps.step3.description": "After cleaning your clothes, we'll bring them back on the date you specified, in the order you requested.",

    // Services
    "services.title": "Our Services",
    "services.dryCleaning.title": "Dry Cleaning",
    "services.dryCleaning.slogan": "Reliably, like the first day.",
    "services.washing.title": "Washing",
    "services.washing.slogan": "By the kilogram, with special care.",
    "services.ironing.title": "Ironing",
    "services.ironing.slogan": "Looking your most stylish.",

    // About
    "about.title": "About Yom",
    "about.description": "Yom is the first platform in our country to offer laundry services to users through a mobile app. Our goal is to help people use their time more efficiently by making laundry tasks easier. Laundry takes more than 3 hours of our time per week and can often be a tedious process. We believe that offering the highest quality delivery and cleaning services, and making them easily accessible to people, is the main path to achieving this goal.",

    // FAQ
    "faq.title": "Have questions? We're here for you",
    "faq.button": "Ask us your question",
    "faq.q1": "Which areas do you serve?",
    "faq.a1": "Currently, we only serve the central areas of Baku. In the near future, we aim to continuously grow and serve all regions of Azerbaijan.",
    "faq.q2": "What hours do the couriers work?",
    "faq.a2": "Of course, at the time that suits you best. You make this choice entirely. Select pickup and delivery times in the mobile app, and leave the rest to us.",
    "faq.q3": "How can I make payments?",
    "faq.a3": "You can pay fully online. Unfortunately, we do not accept cash payments at this time.",
    "faq.q4": "Can I change or cancel my order?",
    "faq.a4": "Of course. Simply notify our customer service and that will be sufficient.",

    // Download
    "download.title": "Your clean clothes are just a tap away",
    "download.description": "Download our mobile app now and start enjoying our service convenience in minutes.",
    "download.scanToDownload": "Scan to download",

    // Footer
    "footer.description": "Professional laundry and dry cleaning services delivered to your door.",
    "footer.services": "Services",
    "footer.laundry": "Laundry",
    "footer.dryCleaning": "Dry Cleaning",
    "footer.express": "Express Service",
    "footer.scheduled": "Scheduled Pickup",
    "footer.company": "Company",
    "footer.about": "About",
    "footer.contact": "Contact",
    "footer.legal": "Legal",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.rights": "All rights reserved.",

    // Contact Page
    "contact.title": "Contact",
    "contact.description": "Get in touch with us. Write to us for your questions, suggestions, or complaints.",
    "contact.info": "Contact Information",
    "contact.address": "Address",
    "contact.phone": "Phone",
    "contact.email": "Email",
    "contact.social": "YOM on Social Media",
    "contact.followLinkedIn": "Follow us on LinkedIn",
    "contact.followInstagram": "Follow us on Instagram",

    // Terms Page
    "terms.title": "Terms & Conditions",
    "terms.lastUpdated": "Last updated: 19.11.2025",
    "terms.section1.title": "1. About us",
    "terms.section1.p1": "\"Yom\" is a mobile application platform that allows users (\"you\", \"your\") to order professional laundry services, including washing, dry cleaning, carpet cleaning, and other related cleaning services. The Platform is operated by Yom (\"we\", \"our\", \"us\") and is registered under Tax Identification Number (TIN/VÖEN) 2005163372.",
    "terms.section1.p2": "Our mission is to make laundry care simple and time-efficient for everyone. Our initial research shows that an average person spends more than 3 hours per week on laundry-related tasks, which are often repetitive and inconvenient.",
    "terms.section1.p3": "Our goal is to provide users with the easiest possible way to manage all their laundry needs — by offering high-quality pickup, delivery, and cleaning services, all accessible through one convenient app.",
    "terms.section1.p4": "Please note that Yom operates as an agent — we do not own or operate any laundry or cleaning centers. Instead, Yom:",
    "terms.section1.li1": "Connects customers with independent service providers; and",
    "terms.section1.li2": "Arranges the pickup and delivery of clothing and other items.",
    "terms.section1.p5": "By using the Yom app, you confirm that you have read and agreed to these Terms & Conditions (\"Terms\").",
    "terms.section2.title": "2. Nature of Yom's Role",
    "terms.section2.p1": "Yom does not own, operate, or control any laundry, dry cleaning, or other cleaning facilities.",
    "terms.section2.p2": "Yom acts exclusively as an agent that:",
    "terms.section2.li1": "Connects customers with independent Service Providers;",
    "terms.section2.li2": "Arranges pickup and delivery of items between you and the Service Provider; and",
    "terms.section2.li3": "Facilitates payment and communication between parties.",
    "terms.section2.p3": "All cleaning services are performed by independent Service Providers who operate under their own business licenses and responsibilities.",
    "terms.section3.title": "3. Acceptance of Terms",
    "terms.section3.p1": "By registering an account, placing an order, or otherwise using the Platform, you acknowledge that you:",
    "terms.section3.li1": "Are at least 18 years old;",
    "terms.section3.li2": "Have read and understood these Terms; and",
    "terms.section3.li3": "Agree to be legally bound by them.",
    "terms.section3.p2": "If you do not agree, please do not use the Platform.",
    "terms.section4.title": "4. Placing Orders",
    "terms.section4.p1": "When you place an order through the Yom app:",
    "terms.section4.li1": "You request pickup and delivery services from Yom.",
    "terms.section4.li2": "Yom, as agent, will allocate your items to one of its partnered Service Providers for cleaning.",
    "terms.section4.li3": "You will not be informed which Service Provider has been assigned, as this is managed internally by Yom to ensure efficiency and quality control.",
    "terms.section4.p2": "Once you confirm your order, you authorize Yom to:",
    "terms.section4.li4": "Act as your limited agent to arrange cleaning services;",
    "terms.section4.li5": "Facilitate communication and payment with the Service Provider.",
    "terms.section5.title": "5. Pickup & Delivery",
    "terms.section5.p1": "Yom will collect items from your provided address at the scheduled time.",
    "terms.section5.p2": "Items will be delivered back once cleaning is completed by the Service Provider. Delivery times are estimates and may vary due to traffic, weather, or Service Provider delays.",
    "terms.section5.p3": "You are responsible for ensuring that:",
    "terms.section5.li1": "All items are correctly described (e.g., fabric type, special care instructions).",
    "terms.section5.li2": "Any existing damages are disclosed before pickup.",
    "terms.section6.title": "6. Payments & Pricing",
    "terms.section6.p1": "All prices displayed on the Platform are inclusive of Yom's delivery/agent service and the Service Provider's cleaning fee.",
    "terms.section6.p2": "Payment is processed through the Platform at the time of order confirmation.",
    "terms.section6.p3": "Yom may change prices or introduce new fees at any time, with changes reflected in the Platform before you place a new order.",
    "terms.section7.title": "7. Lost or Damaged Items",
    "terms.section7.p1": "While Yom and its partner Service Providers take great care handling all items, please note:",
    "terms.section7.li1": "Yom is not responsible for any loss, damage, shrinkage, discoloration, or alteration of items caused by the cleaning process performed by the Service Provider.",
    "terms.section7.li2": "Yom's responsibility is limited to the pickup and delivery of items.",
    "terms.section7.li3": "In case of an issue, Yom will assist you in communicating with the Service Provider to seek resolution or compensation in accordance with the Service Provider's own policy.",
    "terms.section7.p2": "Claims regarding damage or loss must be reported to Yom within 24 hours of delivery.",
    "terms.section8.title": "8. Liability Limitation",
    "terms.section8.p1": "To the maximum extent permitted by law:",
    "terms.section8.p2": "Yom shall not be liable for any direct, indirect, incidental, or consequential damages arising from:",
    "terms.section8.li1": "Acts or omissions of Service Providers;",
    "terms.section8.li2": "Delays in pickup or delivery;",
    "terms.section8.li3": "User-provided inaccurate information or failure to disclose special care requirements.",
    "terms.section8.p3": "Yom's total liability under any claim shall not exceed the total service fee paid for the specific order in question.",
    "terms.section9.title": "9. User Responsibilities",
    "terms.section9.p1": "You agree to:",
    "terms.section9.li1": "Provide accurate pickup and delivery information;",
    "terms.section9.li2": "Ensure items are available for pickup at the agreed time;",
    "terms.section9.li3": "Refrain from including prohibited items (e.g., jewelry, cash, hazardous materials) with your laundry;",
    "terms.section9.li4": "Treat Yom staff and Service Providers with respect.",
    "terms.section9.p2": "If pickup or delivery fails due to inaccurate address or unavailability, Yom may charge an additional delivery fee.",
    "terms.section10.title": "10. Cancellation & Refunds",
    "terms.section10.p1": "Orders can be canceled up to the time of pickup without charge.",
    "terms.section10.p2": "Once items have been collected, cancellation is not possible.",
    "terms.section10.p3": "Refunds (if any) are provided only in Yom's sole discretion or as required by law.",
    "terms.section11.title": "11. Service Modifications",
    "terms.section11.p1": "Yom may modify, suspend, or discontinue parts of the Platform at any time without prior notice.",
    "terms.section11.p2": "We may also update these Terms periodically, and continued use of the Platform indicates acceptance of any new version.",
    "terms.section12.title": "12. Privacy",
    "terms.section12.p1": "Your use of the Platform is also governed by our Privacy Policy, available within the app and on our website.",
    "terms.section12.p2": "By using Yom, you consent to the collection and processing of your personal data in accordance with that policy.",
    "terms.section13.title": "13. Governing Law & Dispute Resolution",
    "terms.section13.p1": "These Terms are governed by the laws of the Republic of Azerbaijan.",
    "terms.section13.p2": "Any disputes arising under these Terms shall first be attempted to be resolved amicably.",
    "terms.section13.p3": "If not resolved, they shall be submitted to the competent courts of Baku, Azerbaijan.",
    "terms.section14.title": "14. Contact",
    "terms.section14.p1": "If you have any questions or complaints, please contact us at:",

    // Privacy Page
    "privacy.title": "Privacy Policy",
    "privacy.lastUpdated": "Last updated: 19.10.2025",
    "privacy.section1.title": "1. Introduction",
    "privacy.section1.p1": "Welcome to Yom.",
    "privacy.section1.p2": "This Privacy Policy explains how Yom (\"Yom\", \"we\", \"our\", \"us\") collects, uses, stores, and protects your personal data when you use our mobile application, website, and related services (\"Platform\").",
    "privacy.section1.p3": "By using the Platform, you agree to this Privacy Policy. If you do not agree, please stop using our services.",
    "privacy.section2.title": "2. Information We Collect",
    "privacy.section2.p1": "We may collect and process the following types of information:",
    "privacy.section2.subtitle1": "a. Personal Information",
    "privacy.section2.li1": "Full name",
    "privacy.section2.li2": "Phone number",
    "privacy.section2.li3": "Email address",
    "privacy.section2.li4": "Delivery and pickup addresses",
    "privacy.section2.li5": "Payment information (processed securely through third-party payment providers; Yom does not store your card details)",
    "privacy.section2.subtitle2": "b. Usage Information",
    "privacy.section2.li6": "App usage data (features used, order history)",
    "privacy.section2.li7": "Device information (model, OS, IP address)",
    "privacy.section2.li8": "Location data (only when you allow it, for pickup and delivery)",
    "privacy.section3.title": "3. How We Use Your Information",
    "privacy.section3.p1": "We use your data to:",
    "privacy.section3.li1": "Register and manage your Yom account",
    "privacy.section3.li2": "Process and deliver your service orders",
    "privacy.section3.li3": "Communicate with you about your orders, payments, or support requests",
    "privacy.section3.li4": "Improve our Platform and customer experience",
    "privacy.section3.li5": "Comply with legal obligations",
    "privacy.section4.title": "4. Sharing of Information",
    "privacy.section4.p1": "We may share your personal data with:",
    "privacy.section4.li1": "Laundry service providers – to perform the cleaning service you ordered",
    "privacy.section4.li2": "Delivery partners or drivers – to collect and return your items",
    "privacy.section4.li3": "Payment processors – to complete your transaction securely",
    "privacy.section4.li4": "Government authorities – if required by law",
    "privacy.section4.p2": "Yom does not sell or rent your personal data to any third parties.",
    "privacy.section5.title": "5. Data Retention",
    "privacy.section5.p1": "We store your information only as long as necessary to:",
    "privacy.section5.li1": "Provide the service; and",
    "privacy.section5.li2": "Comply with legal, tax, or accounting obligations.",
    "privacy.section5.p2": "After this period, your data will be securely deleted or anonymized.",
    "privacy.section6.title": "6. Data Security",
    "privacy.section6.p1": "We use appropriate administrative, technical, and physical safeguards to protect your data from unauthorized access, loss, misuse, or alteration.",
    "privacy.section6.p2": "However, no method of online transmission is 100% secure, and Yom cannot guarantee absolute security.",
    "privacy.section7.title": "7. Your Rights",
    "privacy.section7.p1": "Depending on applicable laws, you may have the right to:",
    "privacy.section7.li1": "Access your personal data",
    "privacy.section7.li2": "Request correction or deletion",
    "privacy.section7.li3": "Withdraw consent for data processing",
    "privacy.section7.li4": "Request a copy of your data",
    "privacy.section7.p2": "You can exercise these rights by contacting hello@yom.az.",
    "privacy.section8.title": "8. Cookies & Tracking",
    "privacy.section8.p1": "Our Platform may use cookies or similar technologies to:",
    "privacy.section8.li1": "Improve functionality and user experience",
    "privacy.section8.li2": "Analyze traffic and performance",
    "privacy.section8.li3": "",
    "privacy.section8.p2": "You may disable cookies through your device or browser settings.",
    "privacy.section9.title": "9. Third-Party Links",
    "privacy.section9.p1": "The Platform may contain links to external websites.",
    "privacy.section9.p2": "Yom is not responsible for the privacy practices of those third parties.",
    "privacy.section10.title": "10. Changes to This Policy",
    "privacy.section10.p1": "Yom may update this Privacy Policy from time to time.",
    "privacy.section10.p2": "Any changes will be published on the Platform with an updated date.",
    "privacy.section10.p3": "Continued use of the Platform means you accept the revised Policy.",
    "privacy.section11.title": "11. Contact",
    "privacy.section11.p1": "If you have any questions or complaints about this Privacy Policy, please contact us:",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("az");

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.az] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
